# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    macos.yml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: thfirmin <thfirmin@student.42.rio>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/18 10:04:52 by thfirmin          #+#    #+#              #
#    Updated: 2023/05/22 00:23:31 by thfirmin         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Name of script
name: 'MacOS Tests'

# Set of event hooks
on:
  push:
  pull_request:
    branches: main

jobs:
  norma-job:
    name: 'Project normalization'
    runs-on: macos-latest

    steps:
      - name: 'Setup'
        uses: actions/checkout@v3

      - name: 'Dependancy instalation'
        run: |
          printf "\e[31mInstalling:\e[m Brew\n"
          rm -rf $HOME/.brew
          git clone --depth=1 https://github.com/Homebrew/brew $HOME/.brew
          echo 'export PATH=$HOME/.brew/bin:$PATH' >> $HOME/.zshrc
          source $HOME/.zshrc
          brew update
          printf "Brew \e[31mInstalled\e[m\n"
          printf "\e[31mInstalling:\e[m Valgrind\n"
          brew uninstall valgrind
          curl https://raw.githubusercontent.com/gabrieldejesus/valgrind-macos/main/valgrind.rb -o valgrind.rb
          brew install --HEAD -s valgrind.rb
          brew install libcunit1 libcunit1-doc libcunit1-dev
          printf "Valgrind \e[31mInstalled\e[m\n"
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette

      - name: 'Norminette validation'
        run: bash .github/norminette.sh

      - name: 'Junkfiles Validation'
        run: bash .github/junkfile.sh

      - name: 'Makefile Validation'
        run: |
          printf "\e[31mTESTING =>\e[m Uses of cc and -Wall -Wextra -Werror flags\n"
          make -n | grep -e 'cc' | grep -e '-Wall' | grep -e '-Wextra' | grep -e '-Werror'
          printf "\e[31mTESTING =>\e[m Mandatory rules of name, all, clean, fclean and re\n"
          make -n cub3D all clean fclean re 1> /dev/null
          printf "\e[31mTESTING =>\e[m Compiling...\n"
          make all LOG=1
          printf "\e[31mTESTING =>\e[m Re-link\n"
          if [ "$(make -n | grep -e "cc")" = "" ]; then { exit 0; } else { exit 1; } fi


